import {Field} from "./types/field";

const background_color: string = "white";
const black_color: string  = "black";
const accent_color: string  = "beige";

const red_color : string = "red";
const blue_color : string = "blue";
const yellow_color : string = "yellow";
const green_color : string = "green";
// 13 + idx
const Board: Field[] = [
  {"color":red_color,"type":"base"},
  {"color":red_color,"type":"base"},
  {"color":background_color,"type":"base"},
  {"color":background_color,"type":"base"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":blue_color,"type":"blank"},
  {"color":blue_color,"type":"base"},
  {"color":red_color,"type":"base"},
  {"color":red_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":blue_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":blue_color,"type":"blank"},
  {"color":blue_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":blue_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":blue_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":blue_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":red_color,"type":"blank"},
  {"color":red_color,"type":"blank"},
  {"color":red_color,"type":"blank"},
  {"color":red_color,"type":"blank"},
  {"color":background_color,"type":"blank"}, // środek układu
  {"color":green_color,"type":"blank"},
  {"color":green_color,"type":"blank"},
  {"color":green_color,"type":"blank"},
  {"color":green_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":yellow_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":yellow_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":yellow_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":yellow_color,"type":"blank"},
  {"color":yellow_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":yellow_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":green_color,"type":"blank"},
  {"color":green_color,"type":"blank"},
  {"color":yellow_color,"type":"blank"},
  {"color":yellow_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":accent_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":background_color,"type":"blank"},
  {"color":green_color,"type":"blank"},
  {"color":green_color,"type":"blank"},
]
export const get_board = (): Field[] => Board;


