import { GamePath, Tile } from '../types/gameTypes';

const bg_color: string = 'white';
const accent_color: string = 'beige';

const red_color: string = 'red';
const blue_color: string = 'blue';
const yellow_color: string = 'yellow';
const green_color: string = 'green';

const game_path = [44,45,46,47,48,37,26,15,4,5,6,17,28,39,50,51,52,53,54,65,76,75,74,73,72,83,94,105,116,114,103,92,81,70,69,68,67,66,55];

export const game_paths: Record<string,GamePath> = {
  "red":{
    game_path:game_path,
    base_points: [10,11,23,24],
    starting_point:44,
    ending_base_entry:55,
    ending_base_path:[56,57,58,59],
  },
  "blue":{
    game_path:game_path,
    base_points: [19,20,30,31],
    starting_point:6,
    ending_base_entry:5,
    ending_base_path:[16,27,38,49],
  },
  "green":{
    game_path:game_path,
    base_points: [89,90,100,101],
    starting_point:76,
    ending_base_entry:65,
    ending_base_path:[61,62,63,64],
  },
  "yellow":{
    game_path:game_path,
    base_points: [96,97,107,108],
    starting_point:114,
    ending_base_entry:115,
    ending_base_path:[104,93,82,71],
  },
  "":{ // nie wiem po co to jest tak szczerze
    game_path:game_path,
    base_points: [],
    starting_point:0,
    ending_base_entry:0,
    ending_base_path:[],
  }
}


export const gameboard: Tile[][] = [
  [
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'ending_point',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: blue_color,
      role: 'starting_point',
      type: 'tile',
      occupied: false,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
  ],
  [
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: red_color, role: 'starting_base', type: 'tile', occupied: true },
    { background_color: red_color, role: 'starting_base', type: 'tile', occupied: true },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: blue_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: blue_color, role: 'starting_base', type: 'tile', occupied: true },
    { background_color: blue_color, role: 'starting_base', type: 'tile', occupied: true },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
  ],
  [
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: red_color, role: 'starting_base', type: 'tile', occupied: true },
    { background_color: red_color, role: 'starting_base', type: 'tile', occupied: true },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: blue_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: blue_color, role: 'starting_base', type: 'tile', occupied: true },
    { background_color: blue_color, role: 'starting_base', type: 'tile', occupied: true },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
  ],
  [
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: blue_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
  ],
  [
    {
      background_color: red_color,
      role: 'starting_point',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: blue_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
  ],
  [
    {
      background_color: accent_color,
      role: 'ending_point',
      type: 'tile',
      occupied: false,
    },
    { background_color: red_color, role: 'ending_base', type: 'tile', occupied: false },
    { background_color: red_color, role: 'ending_base', type: 'tile', occupied: false },
    { background_color: red_color, role: 'ending_base', type: 'tile', occupied: false },
    { background_color: red_color, role: 'ending_base', type: 'tile', occupied: false },
    { background_color: bg_color, role: 'dice', type: 'blank', occupied: false }, // środek układu
    { background_color: green_color, role: 'ending_base', type: 'tile', occupied: false },
    { background_color: green_color, role: 'ending_base', type: 'tile', occupied: false },
    { background_color: green_color, role: 'ending_base', type: 'tile', occupied: false },
    { background_color: green_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'ending_point',
      type: 'tile',
      occupied: false,
    },
  ],
  [
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: yellow_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: green_color,
      role: 'starting_point',
      type: 'tile',
      occupied: false,
    },
  ],
  [
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: yellow_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
  ],
  [
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: yellow_color,
      role: 'starting_base',
      type: 'tile',
      occupied: true,
    },
    {
      background_color: yellow_color,
      role: 'starting_base',
      type: 'tile',
      occupied: true,
    },
    { background_color: bg_color, role: 'blank', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: yellow_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: bg_color, role: 'blank', type: 'tile', occupied: false },
    {
      background_color: green_color,
      role: 'starting_base',
      type: 'tile',
      occupied: true,
    },
    {
      background_color: green_color,
      role: 'starting_base',
      type: 'tile',
      occupied: true,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
  ],
  [
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: yellow_color,
      role: 'starting_base',
      type: 'tile',
      occupied: true,
    },
    {
      background_color: yellow_color,
      role: 'starting_base',
      type: 'tile',
      occupied: true,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: yellow_color, role: 'ending_base', type: 'tile', occupied: false },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: green_color,
      role: 'starting_base',
      type: 'tile',
      occupied: true,
    },
    {
      background_color: green_color,
      role: 'starting_base',
      type: 'tile',
      occupied: true,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
  ],
  [
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    {
      background_color: yellow_color,
      role: 'starting_point',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'ending_point',
      type: 'tile',
      occupied: false,
    },
    {
      background_color: accent_color,
      role: 'gameboard_tile',
      type: 'tile',
      occupied: false,
    },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
    { background_color: bg_color, role: 'blank', type: 'blank', occupied: false },
  ],
];
